---
title: "Introduction to R"
subtitle: "University of Adelaide, Schol of Medicine"
author: "Stephen Pederson, Bioinformatics Hub"
date: "27 June 2016"
output: html_document
---

## This website
https://uofabioinformaticshub.github.io/schoolOfMedicine2016/

## Instructions for Setup

Instructions for setting you computer up can be found [here](00_Setup.html)

## Introduction

The R programming language provides an effective environment for making sense of data that enables us to address various biological questions. 
In this introduction course, we will illustrate exploratory data analysis that involves calculating numerical and graphical summaries. 
For more intermediate participants in the course we will examine more complex visualization tools.

## Topics Covered
- *R* data types
- Using functions in *R*
- Reading data in *R* 
- Exploratory data analysis
- Installing packages

## Course Material

The individual sessions are available at the following sites:

## Today's Data

For those familiar with the version control system `Git`, you can clone the repository using

`git clone https://github.com/UofABioinformaticsHub/schoolOfMedicine2016.git`

Otherwise, just download today's data as a `zipfile` using the following link.

https://github.com/UofABioinformaticsHub/schoolOfMedicine2016/archive/gh-pages.zip

### Data in R
[01 R and Data Types](01_Data.html)  
[02 Vectors and Functions in R](02_Vectors.html)  
[03 Using Data Frames](03_Data_Frames.html)  
[04 Loading Data Into R](04_Loading_Data.html)

### Optional Material
[05 Inspecting Data](05_Inspecting_Data.html)

### Other Resources
[Learn R Using Swirl](http://swirlstats.com/)  
[RAdelaide 2016](http://www.adelaide.edu.au/bioinformatics-hub/workshops/r-adelaide-2016/)
